=== Landet börjar bebyggas.

Människosläktets äldsta historia har utspelats långt bortom det
nuvarande Sveriges gränser. Men ännu återstår för den arkeologiska
forskningen mycket arbete, innan den ens tillnärmelsevis kan våga uttala sig
om under vilka förutsättningar och inom vilka delar av vår jord som
de första scenerna i det stora dramat utspelats. För varje år som går
inlöpa rapporter från grävningsfälten världen runt om märkliga upptäckter
och fynd, som ge nya aspekter och kasta nytt ljus över dunklet, men i
samma mån som dimmorna skingras, i samma mån växa svårigheterna
att tolka de allt rikare skiftningarna i tavlan. Det ligger nära till hands
att tänka sig, att den förhistoriska tidens gåtor så att säga lösa sig av sig
själv, i och med att ett större och mäktigare fyndmaterial träder i dagen,
men man kan lika gärna prägla paradoxen: ju flera fynd, desto större
ovisshet, ty den genom fyndbeståndets tillväxt vidgade synkretsen ställer
vidgade krav och framtvingar till lösning problemställningar av tidigare oanad
omfattning men naturligtvis också av (ur historisk synvinkel) påtagligare värde. Det är någonting som gäller för all arkeologisk forskning, men
kanske främst för de allra tidigaste faserna i utvecklingen.

Det var en tid, då den franska jorden genom en slösande givmildhet
i fråga om fynd tycktes avslöja sig som det område, där människosläktets
vagga stått, men numera äro även de äldsta stadierna i stenålderns
begynnande primitiva civilisation påvisbara över snart sagt hela den europeiska
kontinenten och över stora delar av Afrika och Asien, från England i väster
lill Peking i öster.

Man anser sig kunna räkna med att människan existerat på vår jord
i varje fall sedan åtskilliga 100,000-tals år tillbaka i tiden. Dylika, kanske
för mången fantastiska siffror ha nämligen geologerna på grundval av
beräkningar, uppgjorda efter flera av varandra oberoende linjer, kunnat
hopsummera, när de sökt fastslå tiden för det yngsta, det nuvarande skedet i
jordklotets historia, den s. k. kvartärtiden — och redan från de äldsta
avsnitten av denna äga vi tillförlitliga spår av mänsklig verksamhet, både i
Europa och Asien.

Kvartärtidens inträde bildar upptakten till den stora nedisningens epok,
till istiden. Alla jordens glaciäromraden utvidgades, och i Europa kom
hela den norra hälften av världsdelen, liksom de mellan- och sydeuropeiska
bergskedjorna att ligga täckta av is. I söder löpte den nordeuropeiska
iskanten fram genom sydligaste England mot Rhenmynningen, tvärs genom
Tyskland över Dresdentrakten och sydspetsen av Schlesien in i Polen och
Sydryssland fram till trakten av Kiev, där den böjde mot norr och beskrev
en stor båge mot Volga och Norra Ishavet.

Söder om denna linje fanns inom ett tämligen smalt bälte av mellersta
samt inom stora partier av västra och sydvästra Europa isfritt land, som
erbjöd goda möjligheter för bosättning och mänskligt liv. Det är också här,
som människans första framträdande på den europeiska kontinenten kan
arkeologiskt fastställas.

Den stora nedisningens tid var givetvis inte något skede av absolut
stillastående; man har tvärtom under denna för våra begrepp oändligt långa
epok kunnat konstatera starka omkastningar i temperaturförhållandena,
vilka haft till följd, att kalla, arktiska nedisningsperioder omväxlat med
värmetider med t. o. m. rent tropiskt klimat.

Detta faktum, klimatväxlingarna och de därav betingade
förändringarna av växt- och djurvärldens sammansättning, har satt oss i stånd att
för dessa avlägsna skeden följa den mänskliga kulturens äldsta successiva
framväxt och utveckling på ett förbluffande exakt och innehållsrikt sätt.
Den geologiska forskningens resultat ha nämligen kunnat direkt utnyttjas
för åldersbestämningar av de mänskliga arbetsprodukter (artefakter) samt
skelettrester, som istidens under varierande betingelser bildade skilda skikt
visat sig innehålla. Fyndens läge i grävningsschakten, dels i förhållande till
varandra, dels i förbindelse med de jordlager, i vilka de påträffas, blir direkt
utslagsgivande för deras åldersbestämning, sålunda att dateringen kommer
att bygga på den geologiska och zoologiska miljö, som jordlagren själva
ge möjlighet att rekonstruera. Å ena sidan har exempelvis djurvärlden
skiftat gestalt, i samma mån som temperaturen växlat — det är ingen
tillfällighet, att inte noshörningar och tigrar ströva omkring på den
norrländska tundran, och det är naturligtvis inte heller någon tillfällighet, när
dessa utpräglat tropiska djurarter kunnat påvisas i västeuropeiska
fyndskikt från istiden. Å andra sidan har den fram- och tillbakaskjutande isen
och dess smältvatten under olika förutsättningar bildat nya avlagringar
över redan förefintliga, som tidigare varit föremål för bebyggelse, och på
så sätt ha lämningarna från en dylik bosättning betryggande inkapslats i
sin geologiska omgivning.

Gräva vi oss ned i en sådan istidsavlagring, låt oss säga i exempelvis
Paristrakten, återuppstå för oss, skikt för skikt och i takt med att spaden
tränger djupare ned, växlingarna inom istidens Frankrike i förbluffande
belysning. Vi återfinna här för länge sedan svunna epoker, då de trakter,
där världsstaden nu ligger, befolkades av en primitiv människoras, vars
enda redskap och vapen i kampen för tillvaron utgjordes av grovt
tillhuggna flintor, och som omgavs av en fullt tropisk natur, i vilken en
djurvärld liknande det nuvarande inre Afrikas hade sin hemvist: elefanter,
flodhästar, noshörningar och tigrar. Men i samma lagerserie kunna vi —
om vi ha tur — både över och under detta skikt påträffa avlagringar från
köldtider, då människans livsvillkor ställde sig helt annorlunda och då för
ett kallare klimat mera lämpade djurarter tagit Paristrakten i besittning,
exempelvis mammuten, vildhästen, bisonoxen och renen.

Istidens slutskede markeras av en över vår jord gradvis skeende
förskjutning av temperaturförhållandena, en förskjutning fram mot nutidens
blidare klimat. Denna kom att verka revolutionerande även för den
geografiska bilden längre i norr. De nordeuropeiska ismassornas avsmältning
begynner, isbarriärens kant viker allt längre tillbaka mot norr.

Genom efter allt att döma tillförlitliga geologiska beräkningar, har man kunnat konstatera, att c:a 15,000 à 16,000 år förflutit sedan den tid, då
isranden efter att ha nått fram till Skånes sydkust definitivt började draga
sig tillbaka och lämna rum för de ur smältvattnet uppdykande
landmassorna. Ytterligare 5,000 år senare hade den nått upp i det nordligaste
Skandinavien.

Det geniala beviset för dessa dateringar har den svenske geologen Gerard
De Geer funnit i den lagbundna skiktindelning, som den s. k. varviga leran
uppvisar. Denna avsattes av smältvattnet från inlandsisen på den
dåvarande isdämda Östersjöns botten. Genom senare landhöjningar har denna
botten lyfts upp över havets yta och framträder nu som vidsträckta lerslätter.
Varje varv eller enhetligt sammansatta lagdelning i denna lera har utbildats
under ett år och visar sig bestå av ett kraftigare, ljusare sommarskikt, som
avsatts av det sommartid rikare flödande smältvattnet, samt ett tunnare,
sandblandat vinterskikt. Vart och ett av dessa årsvarvs sträckning har
genom upprepade stickprov i leran kunnat kartläggas över vidsträckta
områden och når i förhållande till det underliggande så mycket längre mot norr,
som isranden ifrågavarande år drog sig tillbaka. Från dylika
utgångspunkter ha så genom beräkningar och undersökningar, som genomförts över
hela Skandinavien, de ovannämnda slutsiffrorna hopsummerats.

De revolutionerande geologiska och klimatologiska förskjutningar, som
den varviga leran illustrerar, ge den europeiska kontinenten en helt
förändrad struktur. Skogen rycker fram och täcker så småningom det förut
öppna tundre- och stäpplandskapet. Den gamla djurstammen försvinner
för att lämna plats för helt nya arter. Jaktviltet framför alla andra blir
numera hjorten, och dess arktiske föregångare, renen, som varit den
slutande istidens främsta villebråd, tvingas att lämna den europeiska
kontinenten och följer den tillbakavikande isranden mot norr för att taga de ur
ismassorna uppdykande nya landområdena i besittning. — I renens spår
följer jägaren, människan.

De äldsta spåren av att människan invandrat till Norden utgöras också
betecknande nog av en serie enkla, tydligt bearbetade renhornsstycken. De äro till antalet 5 från Danmark och 3 från Skåne, men av dessa är det
endast de förstnämnda, de danska, som blivit föremål för en så betydande
utformning, att vi kunna tala om verkliga redskap. Sannolikt ha dessa gjort
tjänst som ett slags primitiva huggvapen och ha tillverkats på så sätt, att
renhornets huvudtagg bildar skaft och en sidotagg nära roten antingen
urholkats för isättande av ett skarpkantigt flintstycke el. dyl. som skärande
egg eller också snett avskurits för att bilda egg utan tillsats av annat
material (se bild sid. 22).

Denna enkla redskapsform, som väl sannolikt har sin upprinnelse i
nyttjandet av renhornet självt utan omständligare bearbetning som tillhygge,
är den nordeuropeiske renjägarens egen uppfinning och saknar
motsvarigheter inom andra samtida och äldre kulturområden nere på kontinenten.
Men det förtjänar framhållas, att vi återfinna den med tämligen exakt
samma utformning långt senare, bland 1800-talets nordamerikanska
indianstammar i Alaska, vilka fört sin kamp för tillvaron under åtminstone delvis
samma betingelser som Nordens första bebyggare under renjägartid.
