=== De första människorna.

Den första kolonisationen av nuvarande svensk mark tycks efter de
fåtaliga fynden att döma mera ha haft karaktären av tillfälliga jaktfärder mot
norr än av bosättning i egentlig mening, men just den senaste tiden har gett
oss en påminnelse om att det om också obetydliga fyndbeståndets
vittnesbörd inte får helt underskattas. Nyligen ha nämligen uppe i nordvästligaste
Tyskland, i Hamburgtrakten, d. v. s. inom ett till Sydskandinavien
omedelbart gränsande och med detta likvärdigt bebyggelseområde, upptäckts
omfattande boplatser från renjägartid med fynd av flera hundratal bearbetade
renhornsstycken samt dessutom också flint- och benredskap, vilka i sin
utformning anknyta till den kontinentaleuropeiska istidens jaktverktyg och
på så sätt ytterligare markera, under vilka förutsättningar Nordens äldsta
kolonisation tillkommit. Hamburgtraktens boplatser kunna förläggas till c:a
8,000 à 9,000 år f. Kr. Från samma tid härröra de nyssnämnda skånska och
danska renhornsstyckena, och dessa ge oss välgrundad anledning
förutsäga, att en vacker dag verkliga boplatskomplex från samma skede skola
komma att dyka upp även i Sydsverige. Men längre norrut tyckas
människans upptäcktsfärder ännu ej ha sträckt sig.
