== Familjen på Ugglehult.

Herr Carl M. Peterson Ur född den 20 april år 1865. Han
har genomgått folkhögskolan och fick där sin andra väckelse.
Den första gavs honom av hans mor, den ännu levande fru Sara
Nilsson, född år 184 2. Den tredje väckelsen fick herr Peterson
av Rösiö, till vilken han kom såsom den första eleven i den första
småbrukskursen. Herr Peterson är ock den första bonde, som
fått statsstipendium för jordbruksstudier, och har bedrivit dessa
studier i Danmark. Till Danmark har han sedan fört sällskap av
studieresande lantmän ocb är den första bonde, som själv hållit,
småbrukskurser. Han är premierad med första pris och har en
mångfald andra utmärkelser.

Hans fru, Mina Peterson, har deltagit i flera kurser och ut
bildat sig till mästerskap på sina områden. Deras enda barn ff
den lilla dottern Svea.

Mor Sara är den som
lagt grunden till Ugglehult.
Tidigt änka tog hon gårdens
skötsel om hand och
ådagalade därvid en ovanlig kraft och
intelligens. Hon kan, säger
Rösiö, Arrhenii stora
jordbrukslära utantill som ett
rinnande vatten. Hon har
ombestyrt uppläggandet av de
20 fot breda stenmurarna och
med egna händer lagt
sten-bottnen i täckdikena för att
få det riktigt gjort. Utrustad
med ett fullständigt
ingenjörshuvud kan hon uppgöra
ritningar till hus, och på
samma gång ägande en läkares
blick har hon förbundit sår
och vårdat de sjuka i orten.
I kökets alla förhållanden är hon lika hemmastadd som i dei
yttre jordbruket och hade redan i sin ungdom sina egna anslag
i köket om hur det ena och det andra skulle vara.

Familjen har en gång varit mäkta förmögen, men förlorat
sin rikedom på en industriell spekulation. En ny förmögenhet äi
nu på väg att skapas av sonen.
