== En mycken upptagen sommar.

Efter det första besöket, som ägde rum på våren, anhöllo vi
att få komma tillbaka fram på sommaren. Svaret blev att vi
voro välkomna när som helst. För att vi skulle få välja lämplig
dag medskickade herr Peterson följande program för sommarens
bästa förevisningssäsong:

Den 28 juni har jag värmlänningar hos mig på Ugglehult
för studiebesök.

Den 1 juli sunnerboiter.

Den 2 juli södra älvsborgare, Srebroare och skaraborgare.

Den 4 juli gottlänningar, som stanna till den 5 juli, då jag
samlar mina kronobergare ocb reser direkt till lantbruksmötet i
Norrköping i sällskap med gottlänningarna.

Den 14 och 15 juli är jag hemma på Ugglehult med mina
kronobergare.

Den 21 juli tar jag emot studieresande från skilda håll på
Ugglehult.

Den 28 juli jämtlänningarna.

Den 30 och 31 juli västra häradsborna, två dagars besök
med främmande föredragshållare, som bekostas av vederbörande
hushållningssällskap.

Den 3 och 4 augusti östboiter, två dagars besök med
främmande föredragshållare, som bekostas av vederbörande
hushållningssällskap.

Den 11 augusti tar jag emot studieresande från skilda håll
på Ugglehult.
