== Den 11 augusti.

Vi valde den 11 augusti. Redan kvällen förut voro vi på

väg dit på tågen, ty herr Peterson hade föreskrivit, att vi skulle
se till att vi voro utvilade till den följande dagens strapatser.
Och mitt ibland de många människorna på vårt tåg var det som
om vi haft känning av varandra. Det var något förväntansfullt
och intresserat i blickarna som kom oss att fråga: Skall ni till
Ugglehult? Vi voro ett halvt tjog på detta tåg, kvinnor och
män, småbrukare <yA amatörer, som snart voro i lifligt samspråk
i olika småbruksfrågor, om Rösiö och hans två lärjungar Gari
Peterson och Nils Larsson. Vid Lamhult mötte två skjutsar från
Ugglehult med utrymme för många, men alla kunde icke få plats.
Några måste gå eller cykla.

Vid den rikt upplysta gården stod herr Peterson ocb bjöd
oss välkommen, varefter vi samlades å föreläsningssalen en trappa
upp, som nu var förvandlad till matsal. Här blev det allmän
presentation. En hel del av oss kände varandra förut genom
Rösiö. Där voro åtminstone nio, som på ett eller annat sätt voro omnämnda i Rösiös skrifter. Där var en, som skött sin
fädernegård sedan han var 11 år, där en annan, en kvinna, som
jämte sina systrar skötte en annan mönstergård, där var en
stationsinspektor, som åstadkommit den yppigaste växtlighet å
rena sanden, en kontorschef vid en av Sveriges mest världsbekanta
fabriker, som drev ett medelstort jordbruk som förströelse på
lediga stunder, en verksam medlem av hushållningssällskapet, som
nyss genomdrivit anställandet av en jordbrukskonsulent, flera vakna
bönder från olika trakter och därtill några släktingar till familjen,
däribland lilla Sveas farmors faders syster, som man kan förstå
den äldsta i sällskapet och vederbörligen hedrad som sådan.

Riklig var denna första måltid vid Ugglehult, och sådana
voro också de följande. Det var kalas varje gång med en
mångfald olika rätter. Mjölk och honung flödade i bokstavlig mening,
och därjämte bjöds fisk och kött och grönsaker i många former.

Sängplatser i stort antal voro iordningställda. Vid vårt
tidigare besök på våren var mor Sara i ivrig verksamhet med
massproduktion av madrasser för de studiebesökandes härbärgerande.

På morgonen samlades vi i matsalen till nytt kalas och flera
flockade sig nu till oss. Vi blevo till sist mellan 30 och 40
personer.
