== I trädgården.

Ringande i en klocka gick herr Peterson därpå i spetsen och
begav sig först till trädgården. Vi stannade vid ett av frukter
överlastat träd och fingo en föreläsning om fruktträdsodling.

— Här vilja vi syna på någonting, Carl Peterson, sade en
av sällskapet och låtsade sig vara syneman.

— Vad då, frågade han.

— Jo, stöd under grenarna, så att de icke brista.

Vi fingo höra att jorden under fruktträden skall hållas öppen.
Men vill man att fruktträdsodlingen skall gå mycket sakta, då
må man låta gräset växa mellan träden. Herr Peterson har 180
fruktträd, dels i trädgården, dels i ängar och backar, där han
gjort inympning på vildstammar. Vi skola icke ha många sorter,
blott tre eller fyra. Då kan det bli ett litet parti att sälja.

I trädgården funnos vanliga köksväxter och ett helt kvarter
med blommor. Men här fingo vi inte stanna länge. Vi skulle
ut på markerna där utanför, herr Peterson nästan springande i
spetsen. Så skulle det fortsätta hela dagen, sade han. Först
skulle vi springa i fem minuter och sedan skulle han prata i fem
minuter.

