== Framför ett dike.

(((dike)))
Nu stannade han vid ett dike, som for tillfället var torrt.

— Det här tycker ni nog icke är mycket att se, sade han.
Det Ir emellertid avloppsdike för åtta tunnland mark däruppe.
Tusentals lass sten äro nedlagda i de täckdiken, till vilka det
hör. Här är nu icke mycket vatten, men ni skulle se på våren I
Principen på Ugglehult är att taga vara på allt och därför taga
vi också vara på regnvattnet, och i detta odla vi fisk. Bäst är
att kunna leda vattnet från en sjö, men har man ingen sådan,
som ligger lämpligt till, så kan man reda sig med regnvatten.
Det är lätt att räkna ut hur mycket regnvatten det blir på ett
givet område. Jag räknar icke med vattnet under en tredjedel av
året, juni, juli, augusti och september. Det mesta kommer i form
av snö, som på våren blir smältvatten. Det avrinner på tre veckor,
och då infångar jag det. Vidare frånräknar jag en tredjedel som
avdunstning. Om jag då har exempelvis 100 tunnland och
medelnederbörden är 550 millimeter, så avräknar jag först en tredjedel
för sommaren, låt oss säga 150 millimeter och en tredjedel för
avdunstning, låt oss säga 150 millimeter, och då återstår 200
millimeter till fiskvatten. Detta är mitt lilla regnområde, och från
detta tar jag vatten till vinterdammen som ligger där. Sedan
har jag det stora regnområdet, några hundra tunnland, dels egen
mark, dels mark, som sluttar till min.
