== Vid vinterdammen.

(((damm)))
(((vinter)))
(((fiskodling)))
— Framåt marsch! Nu gå vi till vinterdammen, men fort
måste vi röra på oss, annars hinna vi för litet i dag.

— I denna vinterdamm plockar jag in fisken för vintern,
alldeles som jag sätter in korna i ladugården. Men det är en
egendomlighet med fisken, att den icke äter på vintern. År det
exempelvis karp, så slutar den att äta, när temperaturen går ned
till 9 grader. Han växer ju icke heller under tiden, utan lättar
något, men så obetydligt, att det icke spelar någon roll. Bara
tre procent. Det vill säga 100 kilo karp minskas till 97 kilo.

— Här hade jag i vintras 6,000 fiskar.

— Som ni ser har jag ankor (((ankor))) på dammen nu. Det är dubbel
användning. Annars skall en vinterdamm egentligen ligga torr
på sommaren. En månad före användningen till fisken tömmer
jag den och luftar ut den ordentligt.

Ännu större avkastning lämnar dammen, om sutare A gå
tillsammans med ankorna. Här finnas nu 168 sutare, som i
våras voro så stora som knappnålshuvud. Nu äro de omkring
12 centimeter.

— De där ankorna tror ni kanske äro fjolgamla, för så stora
se de ut, men låt mig se i mina anteckningar — de äro födda
den 18 maj, alltså icke fullt tre månader ännu. De väga väl i
närvarande stund två och ett halvt eller tre kilo, så att
tillväxten är ju snabb. Nu skola de säljas och en del äro slida
redan. Vi hava inga för vintern utan köpa ägg på våren, kläcka
dem under höns och föda upp dem i konstgjorda mödrar.
