== I skogen.

(((skog)))
Vi äro nu i skogen och herr Peterson håller sin nästa
föreläsning från en sten därstädes.

— Ni ser här ett skogsskifte. Skogen avverkades här för 20
år sedan och den uppväxande ungskogen är ju jämn och vacker.
Här har dock ingen sådd ägt rum. Skiftet är något för smalt.
Det bör vara så brett, att när två träd vid sidorna fällas mot
varandra, så skall det fattas några alnar mellan topparna.
Fröträden stå i söder. Då skall solen i april och maj locka kotten
att öppna sitt fjäll och utsläppa det bevingade fröet. Emedan
skiftet icke är större än det är har det skyddats mot att torka
ut, och den kringstående skogen har skyddat den unga planteringen
mot att slitas och pinas av vinden.

— Finns det en glänta, så få vi hacka upp en grop och så
några frön. Men platsen, där trädet skall växa, behöver skydd
mot solen, och sådant skaffa vi norr om en tuva eller en sten.
Titta själva, så få ni se huru dessa plantor norr om stenarna äro
kraftigare än de som stå i söder. Det behövs bara litet
iakttagelseförmåga.

— Raskt framåt, men se upp med fötterna, så att ni icke
trampa ned några plantor. Nå, nämndeman i Ryssby, skynda på!

— Ursäkta, hallonen frestade mig, men jag hör varje ord.

— Som ni ser är återväxten alldeles tillräcklig, och här har
icke lagts ned en skilling för plantering.

— Stanna nu vid detta skifte. Ni ser här några mindre träd,
som äro undertryckta av ett större. Vad skola vi då göra för att
underlätta tillväxten? Vi skola avverka det större, tänker ni. Tror
ni att de undertryckta då taga sig? Nej, de stå fortfarande
förkrympta, och vi ha blott öppnat marken för solen, med påföljd att
fräken, hallon och lingonris uppträda och jorden blir hård och
förstörd för skogsväxten. Nej, lagen lyder att vi skola avverka de träd,
vilkas krona solen icke når. Solen skall skina på toppen av trädet,
men icke på roten. På detta sätt erhålles den värdefullaste tillväxten.

— Ni ser, att skogsskiftena ligga som åkrar. Har ni icke
så stor skog att ni kan hugga ett skifte varje år, så hugger ni
ett vart tionde, femtonde eller tjugonde år. När träden nått 11
tum vid brösthöjd är lämpligaste tiden för avverkning — då blir
det bjälkar till Danmark och Skåne.

I ojämna skogsbestånd nödgas man bläda ut lämpliga träd och friställa träd med kraftig växt — dock tillses att jorden ej avkalas, så att den blir hård och otillgänglig.
