== Stora tillväxtdammen.

— Nu gå vi från skogsodling och lantbruk till fiskodling
igen. Här är stora regnområdet, och här ser ni den stora
tillväxtdammen. I den släpptes 3,000 av det yngel, varom jag förut
talade. 3,000 såldes på våren. Hela dammen är genomdragen
av diken, och när den tömmes följer fisken dikena utefter till
munken eller avloppstrumman. Dammen är 4,5 tunnland. Här
är ett riktigt skiftesbruk, må ni tro. 1901 avverkade jag skogen,
1902 hade jag havre, 1903 och 1904 klöver och gräs, 1905
karp, 1906 sutare. Alldeles som hos tysken, som också infört
fiske i växtföljden. Den här dammen är en riktig idealdamm.
Mot norr står skogen kvar som skydd mot vinden. Mot söder
är skogen borta, ty dammen skall vara öppen mot solen. Här
skall jag i stället bereda marken för gräsväxt till bete för
ungdjuren. Här kommer på det sättet att ligga som en gräsö mellan
denna damm och den nästa.

— Här ser ni ett fält, som beredes till en ny fiskdamm.
Under de blivande vallarna upptagas diken, som fyllas med lera for
tätningens skull, annars skulle vattnet rinna bort mellan stenarna.

En deltagare: Men kan allt detta arbete betala sig?

Herr Peterson: Min övertygelse är att fiskkulturen här i
Kronobergs län kommer att spela lika stor roll som lantbruket i
nuvarande stund. I Tyskland uppdämdes fälten under medeltiden
för fiskodling. Efter 30-åriga kriget blev säden dyr och man
slog sig på sädesodling. Nu har fisken blivit dyr igen och fälten
sättas under vatten. För resten är det fördelaktigt att växla med
säd och fisk. Produktionen blir då så mycket bättre.

Nu gå vi nedåt sjön.

— Den odlade fisken får en bismak och måste utvattnas i
fjorton dagar i klart vatten. Här är en utvattningsbassäng. Här
förvarar jag för övrigt en del fisk, som jag säljer på hösten.
När det då under vintern blir bröllop i ett finare hus, så kan
jag leverera icke blott kalkoner, utan även karp och sutare. Här
i bassängen kring denna källa har jag min egen matfisk. Här
kan jag bevara en gädda till nyårsafton och julafton, och det
tycker min hustru icke illa om.
