== Vialer.

(((vial, gråvial, vingvial)))
(((Lathyrus, Lathyrus heterophyllus)))
— Här ger ni ett fält med vialer. Detta är gråvialen,
Lathyrus heteropbyllus, vid vilken man fäst mycket stora
förhoppningar. Här ser ni frö av den; det kostar 15 kr. per kilo,
vilket gör 1,500 kr. för en säck på 100 kilo. Man har trott,
att denna växt skulle giva ett 60- till 70-årigt bestånd, och
såsom själv kvävesamlande skulle den endast behöva gödslas med
superfosfat och kali. Här passar den emellertid icke så bra. Den
är egentligen en sandjordsväxt och går i sandjorden ett par meter
djupt. Baron Fägerskiöld på Liden per Skövde har 20 till 30
tunnland av densamma. Torkad till hö, innehåller den lika mycket
äggvita som våra rapskakor. Det påstås att den på vissa trakter
är behäftad med en sorts bitterämne, så att den ej så gärna ätes.

(((vial, ängsvial, gulvial)))
(((Lathyrus, Lathyrus pratensis)))
(((vicker, kråkvicker)))
(((Vicia, Vicia cracca)))
— Här är ängsvialen, Lathyrus pratensis, som också är en
härlig baljväxtplanta. Den kan bli 15 till 20 år och har upp
till 18 och 20 procent äggvita. Och här är Vicia cracca, även
den med ofantligt hög äggvitehalt. Dessa två synas gå bättre till
på dessa jordar än gråvialen.

— Nu gå vi utefter kanten av detta havrefält. Havresorten
är guldregn, den är glest sådd för att giva plats för insåning av
klöver och gräs. Ni se hur hela grunden lyser grön, och havren
räcker mig över axeln.

— Här är en fiskdamm igen. Jag har hållit på med
fiskdammar i fyra år, och jag gör er kanske största nyttan, om jag
talar om mina motgångar. Se nu på dammen först, så kunna
vi sedan lägga oss i backen och prata om motgångarna, medan
vi dricka litet saft och vatten.
