(((fiskodling)))
== En fiskodlares första svårigheter.

(((karp)))
(((damm)))
— Första året jag hade fiskdamm skaffade jag en karphona
och två karphanar och fick omkring tusen yngel. Jag sålde 300
på hösten, de övriga skulle jag övervintra. De dogo på brist av
syre. Följande vår köpte jag 10 eller 12 nya karpar. När jag
tömde dammen fick jag icke mer än två yngel, men därtill en
gädda, som var en halv aln lång. När jag förhörde pojkarna,
kröp det fram, att de en gång vid badning tagit en två tuna
lång gädda och släppt den i dammen för att se hur stor hon
skulle bli. Och hon hade ätit upp hela yngelsatsen. I fjol släppte
jag dit 15 sutare och några karpar. Det var nu som 600
sutare-yngel ihjälpressades i den danska fällan, men med min egen
räddade jag 6,000, varav jag sålde 3,000 och utplanterade 3,000
i den stora sträckdammen för tillväxt. En gång hade jag träffat
avtal om försäljning av 400 karpyngel för 10 öre stycket. Jag
gjorde dem i ordning på kvällen i trekvartstums vatten för att
hämta dem följande morgon, men jag hade icke kommit att tänka
på kråkorna, som också äro läckergommar. På morgonen gingo
60 kråkor och vadade i vattnet och hade ätit upp karpyngel för
40 kr. Det hade varit lätt att skydda sig häremot genom att
spänna ett nät över.

— Emellertid är det ett invecklat maskineri med vinterdammar,
lekdammar och sträckdammar och långsamt att vänta i tre år på
resultatet. Enklare är att köpa halvvuxen fisk, som kan bliva matnyttig på
sommaren. Detta har hitintills stött på svårigheter, men nu är
saken hjälpt genom stiftande av södra Sveriges fiskeriförening, som
just här i Aneboda socken skall anlägga en storartad
fiskodlingsanstalt.

— Ja, nu nog om fisken. Nu skola vi se på annat.
