== Vid mossen.

(((torv, bränntorv)))
Vi ha hunnit till mossen. En lada är fylld med skörden från
översta lagret på denna mark. Från underliggande lager bärgas
en andra skörd i form av bränntorv. Här tagas dubbla skördar
utan såväl brukning som sådd. Torvströet upprives med
klösharv och får ligga i solen och torka. Därpå hopföres det med
en torvräfsa. På hästarnas fötter spännas breda skor av trä, så
att de icke sjunka ned i mossen. Torvströlagret är en halv
meter. Därunder ligger bränntorven.

— Vi ha ju lite skog på Ugglehult, sade herr Peterson, men
det hindrar ej att det är ekonomiskt att taga vara på torven.
Torvupptagningen kostar icke mera än vedhuggningen, och då är
det ju skäl att spara skogen. Under de senaste tre åren bar jag
icke bränt ett träd i min kamin, som står i förstugan och
värmer upp alla rummen.

(((torv, älttorv)))
(((torv, sticktorv)))
— Vi taga älttorv eller sticktorv. När man gör älttorv,
så stampas dyn i vatten som när man ältar lera. Det är icke
så noga, om torvmassan ej är så prima. Man kan till och med
inblanda torvströ. Köpings mekaniska verkstad har ältverk, som
kosta 850 kr. Här gå vi till väga på enklare sätt. Vi gå ned
i dyn med våra träskostövlar och en flåhacka och kasta upp
massan på den plana skiva, som ni se här. Ha vi se’n några
pojkar, som valsa bra, så få de svänga omkring där sä mycket
de orka. Därefter slå vi massan i torvformen. När varje hål är fyllt lyfta vi formen och skaka loss torvbitarna på marken
samt dra formen fram ett slag. Därpå fylla vi den igen. Varje
ruta i formen göres 8 centimeter djup, 16 centimeter bred och
24 centimeter lång. Sedan torvstyckena torkat bliva de
betydligt mindre. När torven legat på marken i 14 dar stapla vi upp
den, och efter ytterligare åtta dar köra vi in den. Tror ni torven
är sämre än ved? Den är bättre. 100 kilo torv alstra lika
mycken värme som 183 kilo ved.

Herr Peterson tar en liten torvspade i handen.

— Den som har väl förmultnad och rotfri dyjord kan lätt
sticka upp torv på det här sättet. Man får den då i fyrkantiga
stycken, som läggas upp på fältet att torka. Man kan mycket
väl bränna sådan här torv i vanlig kakelugn, bara man lägger
ett rost under, så att det blir luft. Ett sådant rost kan man
köpa i vilken järnbod som hälst för 75 öre.
