== Stenmuren och grönfoderfältet.

Nu återvända vi till gården. Herr Peterson stiger upp på
den stenmur, som omger inägorna. Den är 20 fot bred. Tjugu
personer skulle kunna stå där i bredd.

— Jag har gått upp på denna mur, sade herr Peterson, för
att visa vad vi haft att tas med. Minst lika mycket sten ligger
i täckdikena, och lika mycket finnes kvar än i fälten.

Närmast innanför muren på denna sida ha vi
grönfoderfältet. Där torkas å hässjor det grönfoder, som icke hunnit
uppfodras. Där grönfoder blivit skördat har jorden omedelbart
blivit behandlad med fjäderharv och öppnad för luften. En man
håller på att hänga grönfoder på hässjor.

— Vi kunna ej uppfodra allt grönfoder och därför torkas
en del till hö. Djuren få sådant hö — det innehåller 14 procent
äggvita — tillsammans med rotfrukter. Härigenom minskas
åtgången å kakor. Somliga vilja, att man med baljväxter skall helt
och hållet ersätta kakorna, men med nuvarande kakpris anser jag
kakutfodringen ekonomiskt bärig.

(((ärt, åkerärt)))
(((lupin)))
— Här, sade herr Peterson, och tog ett steg in bland
peluskerna, vill jag visa ett exemplar av lupinen, som är den kraftigaste
kvävesamlare vi ha bland våra baljväxter. Den duger icke för
utfodring, ty den har ett bitterämne, men är lämplig som
förfrukt till exempel till potatis. Medan den är i blomning plöja
vi ned den, och vi få jorden i en växtkraft som blir ofantlig.

— Här är potatis på vall. Det är latmansmetoden för
potatisodling. — Den beskrives längre fram.

(((vicker, luddvicker)))
(((vicker, sommarvicker)))
(((Vicia, Vicia sativa)))
(((Vicia, Vicia villosa)))
— På det här fältet taga vi andra skörden för i år. I
höstas sådde vi luddvicker och råg, som togs som grönfoder
mellan 1:sta och 15:de juni. Därefter övergödslade vi fältet, och
sådde vi sommarvicker med pelusker och bönor och på det sättet
få vi sent grönfoder, tills rotfrukterna komma.
