== Å morotsfältet.


(((morot)))
(((Daucus, Daucus carota)))
— Nu hoppa vi över det där stängslet och titta på
morötterna. Vi marschera genom fältet. Det är finaste
trädgårds-morötter allihop, Sanct Valerie — det blir många soppor av det
här. Sven Johan, skall du inte också i år köpa några vagnslaster
för Norrland? Sedan gå de i Östersund och Lakaträsk för 5 öre
bunten. Skulle du inte vilja, så få korna äta upp dem. Blasten
få de i alla händelser, den innehåller mer äggvita än roten, och
räcker åt dem en månad från första oktober till första november.

Respekten för vår vägvisare stiger för varje steg. Han har
drivit sina arbeten och odlingar till en fullkomlighet, som utvecklar
skönhet hos allt vad man ser. Så är det med dessa oräkneliga
bataljoner av morötter, vilkas gröna stjälkar 7aja som hjälmbuskar
i snörräta, ogräsfria led. Han har rotfrukter på sex tunnland av
sjutton. Med sin massa och sina kolossala former imponerar också
fältet av kålhuvuden. Han har över 2,100 av den sorten.

Till sist beskåda vi bönplanteringen och försumma därvid
icke att undersöka bönornas rötter, där bakterieknölarna sitta så
stora som rågkorn.

— Nu ha vi gått stora ringen, säger herr Peterson. Efter
middagen gå vi lilla ringen, och den är icke mera ansträngande
fin att farmors fars syster kan följa med och se hur de unga ha
det.

Å föreläsningssalen var middagen dukad. Skulle något
anmärkas emot den, så skulle det vara, att den kanske var något
för överdådigt tilltagen med sina många rätter. Men något
dåsande efter middagen kom ej i fråga. Så snart vi slutat måltiden
skyndade vi ut igen och övergingo nu till »lilla ringen». Den
böljade med en föreläsning vid hönshuset.
