== Vid hönsgården.

— Vårt land inför ägg för mellan 4 och 5 miljoner kronor,
sade herr Peterson. Vi borde dock mycket lätt kunna själva fylla
detta behov. Det första villkoret för hönsskötsel är att hönsen
få en egen bostad. Den gamla lanthönan är försvagad genom
inavel, klen och spenslig, lämnar allt för få ägg och för små ägg.
Skaffa några bra ruvägg, renrasigheten spelar mindre roll. En
god korsning är lika bra. Vi lägga aldrig en höna i taget, utan
5, 8 eller 10 på en gång. Under varje höna lägga vi 11 eller
13 ägg, och blir det icke udda, så går det lika bra. En
grästorva skall hon ha under sig, upp- eller nedvänd spelar mindre
roll, huvudsaken är att det blir fuktighet. När hönan värper
ute lägger hon alltid sina ägg på en grästorva. Och då hon
intagit sin plats på äggen lägga vi gärna locket på lådan.
Sedan ha vi ingenting mera att göra den dagen. Dagen därpå
släppa vi ut hönan, men endast för en timme i taget. Går hon
icke in igen, så driva vi in henne. Lika högt jag värderar den
konstgjorda modern, lika litet uppskattar jag
äggkläcknings-maskinerna. Har man höns av korsningsproduktion kan man
mycket väl få ruvare. Vi kläcka ett par hundra kycklingar om
året, och det går utmärkt med blott höns och kalkoner som
ruvare.

— När äggen legat i åtta dar, så tar man upp dem och
klarar dem. För ändamålet finnes en lampa med tub. Tuben
kan man göra själv av ett stycke papper från spetsen av en
sockertopp. Är ägget befruktat finnes i detsamma en liten mörk
fläck, är det icke befruktat, så är det klart. De klara äggen
kunna användas till mat, ty de ha icke hunnit skämmas än. Ha vi nu lagt tio hönor, så klara vi kanske bort så många ägg, att
vi kunna köra upp ett par att börja värpa igen.

— Kycklingarna behöva ingen mat första dygnet. De ha
matsäck med sig. Ge vi dem mat kunna vi förstöra dem — de få
diarré och dö. De äro ej vana vid att mottaga föda än.

— Tjugufyra timmar efter kläckningen placera vi kycklingarna
i en konstgjord moder. Här är en sådan. Den är bättre än hönan,
ty när hon gör sina vida strövtåg ute på markerna kan hon lätt
förlora flera kycklingar. Värme fås från den underliggande
lampan, som brinner natt och dag. Här kunna vi ha 100 kycklingar.
Runt omkring sätta vi stängselnät, och så släppa vi ut kycklingarna
varje dag. Så snart de betat av den gröna fläcken kring modern
flytta vi denna till en annan grön fläck.

— Som första mål få kycklingarna vetebrödssmulor, doppade
i råa äggulor, och därmed fortsättes varannan timme andra och
tredje dagen. Därtill kommer havregryn, skummjölk, absolut frisk,
icke blåsur — då få de ont i magen. Efter ungefär tvenne veckor
ha de utvecklat sig så mycket att de kunna undvara den
konstgjorda modern, och då flytta vi dem till små kullhus. Så snart
man kan se skillnaden på hönor och tuppar sälja vi bort tupparna,
även om de betalas med endast 50 öre stycket. Håller man dem
längre äta de upp sig. Får man dem färdiga före midsommar
betinga de vanligen ganska höga pris. De äro säljbara då de icke
äro mycket större än sparvar.
