== Torparmors konstgjorda moder.

— Priset på denna konstgjorda moder är 33 kr. Ni tycker
kanske att det är för dyrt. Då vill jag visa er torparmors
konstgjorda moder, som är så billig att envar kan bestå sig med den.

— Vi taga först en vanlig packlåda. Är jag en torparmor,
så kan jag få en sådan låda på köpet, när jag handlar för 10 öre
socker i boden. I denna låda ställer jag en mjölktransportflaska
och packar hö omkring. Dagen efter kycklingarnas kläckning
sätter jag på spiseln en gryta med vatten och slår flaskan full
av varmt vatten på kvällen. Nätterna äro ju litet kallare. Över
den första lådan sätter jag en annan, som jag spikar ihop själf.
Över transportflaskan göres ett hål, och över hålet sättes en hatt,
som man klär med tyg. Slutligen läggas fönster ovanpå den
översta lådan, med någon lutning så att vattnet kan avrinna.

Här plockar man in 50 kycklingar ocb här få de så varmt och
gott och tänka att det är mor. Man får dock se till att det blir
luftväxling. Mer än 35 grader får det icke gärna vara. Köp
därför en termometer. De små måste ut, därför göra vi en lucka
på sidan, och till den luckan leda vi en brygga, och så få de gå
ut varenda dag. På kvällarna mota vi upp dem igen. Vi
behöva icke värma upp vattnet mer än varje kväll. Om vi ställa
dit det vid 8-tiden på kvällen, så håller det sig över natten.
