== Hönsstammen.

— Den hönsstam, som finnes här, är en korsningsprodukt.
Yi började för många år sedan med vit leghorn, men tyckte att
den var för klen. Därför skaffade vi oss en wyandottetupp för
överkorsning. Sedan ha vi vartannat år haft wyandottetupp och
vartannat år leghorn. Och resultatet har blivit mycket gott. Yi
få upp till 220 ägg, ja i ett fall 258 per år och höna,
medeltalet är lägre.

— När vi nu veta att hönsen under tredje året icke lämna
mer än hälften så många ägg mot ett av föregående år, så märka
vi åldersklasserna, så att vi kunna göra oss av med dem, då de
bliva två och ett halvt år. De som äro födda första året få en
ring om högra benet, de som äro födda andra året få en ring
om det vänstra, och det tredje årets höns få ingen ring alls.

— Men det är icke nog härmed. Det gäller ock att välja
ut de bästa hönsen för avel. Till följd av nedärvningslagen kan
en böna, som lämnat 220 ägg, fortbringa denna förmåga till
kommande generation. Därför fäster man vid varje höna ett
nummer och kontrollerar de enskildes värpning.

— Nu komma vi till en mycket ömtålig punkt.
Hönsskötseln har blivit så fin, att prinsessor och grevinnor sysselsätta
sig med den, och dessa fina människor ha uppfunnit något, som
kallas kontrollreden. Men dessa äro så opraktiska, att de äro
alldeles odugliga. De taga genom eftersyn vaije timme allt för
mycken tid från småbrukaremors nödvändigare arbeten. Yi få i
stället på det gamla vanliga sättet känna om hönsen ha ägg och
följande eftermiddag kontrollräkna äggen vid insamlingen. Och
det är nödvändigt att göra det. Vi böra icke taga avelsägg av
andra än dem som lämnat minst 180 ägg.

Efter detta gå vi in i hönshuset. Herr Peterson fortsätter.

Morgonfodringen får icke vara
så blöt, att hönsen måste stå och putsa näbben oupphörligt. På
kvällen få de en handfull ren säd. Mellan fodertiderna kunna vi ock
kasta in en handfull säd, så att de få rörelse. Träkol äro
ypperliga att ställa in för hönsen att hacka i. Kolen upptaga en del
syror i hönsens matsmältningsorgan, varigenom dessa fungera bättre.
Torkade nässlor äro bra att skära i hackelse till hönsfoder. Jag
bereder dem på kvällen genom att slå hett vatten på dem.
