== Redskap.

Vi börja nu med redskapen.

— Här ser ni en potatisspjällåda. Jag går ut på morgonen och
ser efter hur lång tid det tar att plocka en sådan låda full och
därefter betalar jag. Spjällådorna användas även till förvaring av potatisen.

— Här är en cambridgevält. Numera kan icke ett tidsenligt
jordbruk bedrivas på klappersstensjord utan en sådan vält. Genom
arbete med densamma hindras uttorkningen av jorden. Den
kostar 95 kr., men det är väl använda pengar.

— Här är Rudolf Sachs radsåningsmaskin. Låt oss prova
den här å backen. Den är den minsta av alla och lämpar sig
för den stenbundna jorden här. Billarna äro ställbara. Såbredden
är en meter. Den är litet dyr, 130 kr., och fås från Andrew
Hollingworth, Örebro.

— Här är en ogräsharv från Köpenhamn, som kostar med
frakt och tull 83 kr. På klapperstensjordar får man gå efter
med cambridgevälten.

— Här ha vi hästhackan från Planet Junior för rensning
av rotfrukter. Ställbar på bredden, ställbar på djupet. Dessutom
en hel mängd handhackor av olika typer.
