== I köket och mejeriet.

Klockan ringer.

— Mor har lovat att vi få gå genom köket.

Där var nu allt i fullständig ordning, ehuru blott en halv
timma förflutit efter den stora måltiden.

— Här är köksspisen, och där är plats för ved. Här är en
varmugn, där maten hålles varm, om icke alla kunna komma in
på ea gång, vilket är svårt, då här är 13 till 15 arbetande
personer varje dig. Här är vårt lilla hushållsmejeri och där är
smörkärnan. Mor håller på den gamla sortens kärna. Men taket sitter en fjädrande stång, som drar upp stöten. Yi kärna
12 till 15 kilo smör i taget. Här är smörältningsbordet och
smörvågen. Här är isgraven, där vi sätta mjölken till avkylning.
Här är mjölkvågen, där vi först väga mjölken, så att vi se att
vikten stämmer med vikten från ladugården. Kontroll på kontroll!
Här sker bokföringen. Här är ett rum för mottagning av smör
från våra leverantörer här i orten.

— Mjölken slås genast
på separatorn. Den bör då
icke vara avkyld till mer än
80 grader. Är temperaturen
lägre uppvärmes mjölken med
varmt vatten. Så fort
separeringen skett sättes grädden i
isvatten. Om vi samla grädde
från 3 eller 4 dagar, så få vi
icke utan föregående
avkylning blanda den yngre med
den äldre. Skummjölken
avkyles, men den som kalvarna
skola ha får behålla den för
dem behagliga ljumma smaken.

— Sedan göra vi smör.
Syrning är en svår sak, och

lättare är att tillverka sött smör. I 6 till 12 timmar får smöret
ligga för avkylning. Sedan sker den andra bearbetningen. På en
diskbänk med marmorskiva uppväges ett kilo, varpå det formas i
den där formen. Men dessförinnan doppa vi formen först i varmt
och sedan i kallt vatten, för att smöret skall släppa.

— Här i trakten är mellan 80 och 40, som göra på samma
sätt och som komma hit varje torsdagseftermiddag med sitt smör,
och så får var och en ett nummer, som slås på med en stämpel.
Jog har för stämplingen låtit fotografera min vackraste ko. Hon
heter Nuna och mjölkar 4,997,6 liter. Vern vill ha ett fotografi
av Nuna? Upp med edra anteckningsböcker, så slå vi dit henne!

— Ett eget rum bör man ha för mejerihanteringen, om man
skall få prima vara. Förvarar man till exempel sill eller
pepparrot i samma rum, så blir det bismak.

Nu äro vi ute på gården igen. Där hänger ett litet skåp
med dörr av fin järntrådsnät.

— Även om vi äro småbrukare, så vilja vi äta litet kött
ibland. I is blir köttet lätt segt. Hänges det ut i fria luften, så
blir det mera mört vid användningen. Vi hänga in det i det där
skåpet, innan en enda fluga kommit i beröring med det, och då
håller det sig i åtta dagar i värsta sommarvärmen. Det kan
köpas från järnhandlaren Sandvall i Jönköping.
