== I bigården.

— I och med uppfinnandet av det rörliga bygget kom
biskötseln i ett nytt läge, ty därmed blevo vi herrar över bina.
Vi dela gärna bi »Oingen i två avdelningar, ett yngelrum och ett
skatterum, i vilket senare vi anbringa översatslådor. Här är
cementpressen, med vilken vi pressa kakbottnar. Vi ha gjort den själva. Här är slungaren. Låt oss ta ut en ram. Eld på
rökaren således! Det är en smal sak att hålla bina i schack.
Celllocken taga vi bort på det här sättet med avtäckningsgaffeln.
Och sedan in med ramen i slungaren! Den honung vi nu slunga
skola vi äta upp till kvällsmat. Det är ju rask expedition. Sedan
sätta vi in ramen igen för att låta den fyllas på nytt.

— Bina övervintra bättre utan honung än med honung,
därför att det händer att honungen försockras, blir som sockergryn,
så att de ha svårt att njuta av den utan vatten. Och då
honungen kan säljas för 1,25 upp till 1,80, beroende på kvalitet, och
sockret fås för 60 öre, så är det förmånligt att slunga ut all
honung på hösten och fodra med sockerlösning, så att bina få
vinterförråd. Det kan vara gjort på tre eller fyra nätter.

— Då honungen blivit litet grumlig röra vi kraftigt om
den och då försockras den icke. Sedan tömma vi den på burkar,
som överbindas med pergamentpapper. Hvarje burk får väga till
ett halvt kilo. En sådan burk ställa vi fram på matbordet som
en ansjovisburk, och när vi sälja honungen, så sända vi omkring
dessa burkar. Burken kostar 10 öre. Få vi den tillbaka, så
avräkna vi således 10 öre.

— Här ser ni en första klassens bikupa från Håkansson,
adress: Hagesskruv, Sävsjöström.

— I översatslådorna är förmånligt att ha drönareceller, de
äro lättare att slunga ut.

— Botten i kupan är vridbar. Den är så inrättad, att när
den för vintern vändes blir utrymmet större. Det är nämligen
flera samhällen, som dö av kvävning än av brist på mat. Kupan
kostar 15 kr. utan bin. Det är ett högt pris, men den är
förträfflig i sitt slag.

— Här en foderapparat. Hàr slår man sockerlösningen.
Bina spatsera upp på matförrådet och dra in ett halvt kilo till
och med ett helt kilo på en natt. 37 grader varm skall
lösningen vara.

— Svagare svärmar och höstbin sammanslås med andra
samhällen. Men därvid kan det hända, att bina bita ihjäl varandra,
då de icke känna igen varann på lukten. För att hindra detta
blåsa vi på dem en sockerlösning med inblandning av några
droppar pepparmyntolja. Det göres så här med den här apparaten
och företages 20 minuter före föreningen. Bina komma då att
lukta likadant och gå bra ihop.
