name: Book 1618504

on:
  push:
    paths:
      - books/1618504/**
      - .github/workflows/1618504.yml

jobs:
  build_book:
    runs-on: ubuntu-latest
    name: Press 1618504
    steps:
      - uses: actions/checkout@v4
      - uses: enjikaka/asciidoctor-convert-action@v0.24
        with:
          inputBook: books/1618504/index.adoc
          outputDir: build
          outputName: "1618504"
      - uses: actions/upload-artifact@v4
        with:
          name: book-1618504
          path: |
            build/1618504.epub
            build/1618504.*.pdf
