name: Asciidoctor

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: reitzig/actions-asciidoctor@v2.0.1
        with:
          version: 2.0.18

      - run: asciidoctor-epub3 books/161854/index.adoc -o build/$(book).epub
